version: "3.7"

services: 

  postgres:
    image: "postgres" # use latest official postgres version
    restart: always
    environment: # configure postgres 
        - POSTGRES_USER=user
        - POSTGRES_DB=Birthday
        - POSTGRES_PASSWORD=password123
    ports: 
        - "4040:5432"
    volumes: # persist data even if container shuts down
        - postgres_data:/var/lib/postgresql/data1/


      
volumes: # named volumes can be managed easier using docker-compose
  postgres_data:
