version: "3.7"

services:

  #ui:
  #  build:
  #    context: .
  #    dockerfile: src/frontend/Dockerfile
  #  ports:
  #    - 4200:80
  #  restart: on-failure
  #  depends_on:
  #    - "api"

  #api:
  #  build:
  #    context: .
  #    dockerfile: src/backend/Advertisement.PublicApi/Dockerfile
  #  ports:
  #    - 80:80
  #  environment:
  #    - ConnectionStrings__PostgresDb=Server=postgres;Database=Advertisement;Username=ad_user;Password=password123;Port=5432
  #  depends_on:
  #    - "postgres"

  postgres:
    image: "postgres" # use latest official postgres version
    restart: always
    environment: # configure postgres 
        - POSTGRES_USER=user
        - POSTGRES_DB=Birthday
        - POSTGRES_PASSWORD=password123
    ports: 
        - "5432:5432"
    volumes: # persist data even if container shuts down
        - postgres_data:/var/lib/postgresql/data/


      
volumes: # named volumes can be managed easier using docker-compose
  postgres_data:
